# Generated by Django 6.0.1 on 2026-03-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('idno', models.IntegerField(max_length=100)),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
