# Generated by Django 6.0.1 on 2026-03-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='date',
            field=models.DateField(default='2026-03-14', max_length=100),
            preserve_default=False,
        ),
    ]
