# Generated by Django 4.2.29 on 2026-03-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0002_attend_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attend',
            name='date',
        ),
        migrations.AlterField(
            model_name='attend',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='idno',
            field=models.IntegerField(),
        ),
    ]
