# Generated by Django 4.2.29 on 2026-03-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0003_remove_attend_date_alter_attend_id_alter_attend_idno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attend',
            old_name='idno',
            new_name='roll',
        ),
    ]
