# Generated by Django 4.2.29 on 2026-03-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0004_rename_idno_attend_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='tarikh',
            field=models.DateField(default='2026-03-14'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attend',
            name='attendance',
            field=models.CharField(max_length=200),
        ),
    ]
