# Generated by Django 4.2.29 on 2026-03-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0005_attend_tarikh_alter_attend_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='faces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
