# Generated by Django 4.1.13 on 2026-03-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0006_face'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Face',
        ),
        migrations.RemoveField(
            model_name='attend',
            name='name',
        ),
    ]
