# Generated by Django 4.1.13 on 2026-04-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0007_delete_face_remove_attend_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attend',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
