# Generated by Django 4.1.13 on 2026-04-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0009_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='classname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
