# Generated by Django 4.1.13 on 2026-04-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0010_entry_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='status',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
