# Generated by Django 4.1.13 on 2026-04-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0011_attend_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attend',
            name='status',
        ),
    ]
