# Generated by Django 4.1.13 on 2026-04-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0012_remove_attend_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='classname',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
