# Generated by Django 4.1.13 on 2026-04-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0013_attend_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='tarikh',
            field=models.DateField(null=True),
        ),
    ]
