# Generated by Django 4.1.13 on 2026-04-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0017_alter_attend_tarikh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='tarikh',
            field=models.DateField(default=10),
            preserve_default=False,
        ),
    ]
